### ISSUE TITLE
Auth service documentation is incorrect in JS section

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/wedeploy.com#126]
Currently in Sign-in sections in Auth, the creation of an instance of Auth is suggested to be done in the following way:

```var auth = WeDeploy.auth();```
 
Instead, it should be ```var auth = WeDeploy.auth('http://<serviceID>.<projectID>.wedeploy.io');```, as properly written currently in [Getting started](http://wedeploy.com/docs/auth/getting-started.html) page.

The problem is in this scenario:
1. Developer initializes `data` service, for example `var auth = WeDeploy.data('http://<serviceID>.<projectID>.wedeploy.io');`
2. Then he visits the documentation page and reads he has to do `var auth = WeDeploy.auth();`
3. He does it and when he tries to execute some operation, for example to create an user, a request to the data service will be made, instead to the `auth` service, for example: `http://data.test.wedeploy.io/users`. If `users` collection doesn't exist (and it doesn't by default), the developer receives 404 page.

**Comment by zenorocha** [comment]
You're right, thanks a lot for sending this PR @ipeychev!
