### ISSUE TITLE
[Docs: data] Add more examples for basic conditional data search

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/wedeploy.com#142]
How to use `.where` ?

ex:

-  `.where('email', 'my@domain.com')`
-  `.where('price', '> ', 10)`

How to simulate SQL LiKE with client? (to get things starting with `x`)

ex:

- Give me all the people with name starting with `a` ?
- `.match('name', 'a' )`

**Comment by zenorocha** [comment]
I noticed that `match` is already documented on http://wedeploy.com/docs/data/searching-data.html.

![](https://d2ppvlu71ri8gs.cloudfront.net/items/02063q363L132x432f38/Screen%20Shot%202017-04-14%20at%202.16.02%20PM.png?v=68c35857)

But `where` isn't, so we should definitely add it.

**Comment by pragmaticivan** [comment]
@zenorocha it was just an example actually. to give all people starting with `a` is actually something more advanced. such as:

```
.where(Filter.prefix('name', query));
```

Sorry about that.


Also, that may generate some questioning about if we should have a `.prefix` in the Data client scope.

**Comment by zenorocha** [comment]
Can we close this one @jonnilundy?

**Comment by jonnilundy** [comment]
Fixed by #362
