### ISSUE TITLE
Tutorial Problem - I wasn't able to send an email

### ISSUE THREAD

**Issue by anitaderiane** [wedeploy/wedeploy.com#145]
> URL: /tutorials/email-web/send-an-email.html 

I filled in the form and clicked on "submit" but nothing happened (no email, no message). 
http://hosting.anita-email.wedeploy.io/

**Comment by jonnilundy** [comment]
@anitaderiane Let's connect today so I can check your project to see what might be the problem. :)

**Comment by jonnilundy** [comment]
@anitaderiane Did we ever resolve this?

**Comment by anitaderiane** [comment]
No sorry. I still need to try again.
