### ISSUE TITLE
Document supported Data types

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#160]
What data types (ie. string, date, int, float, image, objectId, etc) are supported by the Data Service?

**Comment by jonnilundy** [comment]
@pragmaticivan Do you know the answer to this?

**Comment by pragmaticivan** [comment]
@jonnilundy so far the ones I know it supports are: `Boolean, Double, Float, Integer, Long, NestedDocument, String`

**Comment by jonnilundy** [comment]
@pragmaticivan K, I'll just work off this list. Thanks!  
Is this list easily derived from the source code anywhere so we can verify in the future?

**Comment by jonnilundy** [comment]
I will include this in my data doc revamp (#362)

**Comment by zenorocha** [comment]
Closing since #362 was merged.
