### ISSUE TITLE
Document `.auth()` for email

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#162]
Currently, [we encourage users](https://github.com/wedeploy/boilerplate-email/blob/js/hosting/main.js) to use their master token in their client-side scripts which is a huge security risk and should never be encouraged. We must [better document](http://wedeploy.com/docs/email/sending-email.html) how to use the master token and also, what are non-revealing workarounds. There are two I know of now:

1. Use a back-end to send emails so you don't show the token.
2. Authentic with a user rather than using the master token: 
```
WeDeploy.auth('email@wedeploy.com', 'pass')
```

**Comment by NolanChan** [comment]
Would we be able to configure the `environment variables` section in the `container.json` to allow for a master-token? I feel like this would be the most natural solution given what we've implemented

**Comment by jonnilundy** [comment]
I'm going to close this now because technically `.auth()` is documented clearly in the docs. We can look later at other solutions.
