### ISSUE TITLE
Using the CLI page has a link to a wrong target

### ISSUE THREAD

**Issue by mdelapenya** [wedeploy/wedeploy.com#163]
In the paragraph:
```
If you use Windows, you probably want the Windows amd64 installer. For other systems, check a list of all builds available
```
the last link (all builds available) points to a specific version of the CLI, instead of the list of all builds available.

Actual target: https://bin.equinox.io/c/8WGbGy94JXa/cli-stable-windows-amd64.zip
Expected target: the list of all builds available

**Comment by henvic** [comment]
It should be https://dl.equinox.io/wedeploy/cli/stable
