### ISSUE TITLE
Improve the documentation about sign in with OAuth in React Native and React VR environments

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/wedeploy.com#165]
Currently on the site is written that sign in with Facebook, Github, Google, etc. is not supported on React Native environment. Since https://github.com/wedeploy/api-js/issues/119, this is no more true and we have to update the documentation.
More explanations should be added, since achieving sign in with OAuth requires some efforts on the client side too.

**Comment by ipeychev** [comment]
Hey @zenorocha, @jonnilundy,

Here is the draft. Now we have to decide where to put it. The point is that it is valid for all three providers - Facebook, Google and Github. 
We either have to make it a separate page and reference it, or we have to copy it to the pages for Facebook, Google and Github. How would you suggest to proceed?

[oauth-react-native-vr.md.txt](https://github.com/wedeploy/wedeploy.com/files/958826/oauth-react-native-vr.md.txt)

Thanks,

**Comment by ipeychev** [comment]
Okay, meanwhile I went ahead and sent the [PR](https://github.com/wedeploy/wedeploy.com/pull/166) :)

**Comment by zenorocha** [comment]
Closing now that this content is on the help center.
