### ISSUE TITLE
Numbered Lists on "Using the Command-line Interface" do not follow sequence

### ISSUE THREAD

**Issue by alexandervalencia** [wedeploy/wedeploy.com#176]
The ordered list in the "Running Projects Locally" section of the docs/intro/using the command-line interface page does not properly render as a sequential list. Instead each li:before is listed as "1"

Picture for reference. Tested in Chrome (latest), Firefox (latest), and IE11.

<img width="540" alt="2017-05-11 18_36_04" src="https://cloud.githubusercontent.com/assets/22045453/25978960/7a99797e-367a-11e7-8d0d-751211cbeba1.png">

**Comment by alexandervalencia** [comment]
It seems that it has to do with how the .md is being compiled.

Instead of using md's lists:
````
1.
2.
3.
etc.
````
It should be written using html:
````
<ol>
    <li>
        text
    </li>
</ol>
````
I'll send a PR on this soon

**Comment by zenorocha** [comment]
Thanks @alexandervalencia!

**Comment by jonnilundy** [comment]
fixed with #178
