### ISSUE TITLE
Tutorial Problem: theres no command here

### ISSUE THREAD

**Issue by reizero00** [wedeploy/wedeploy.com#186]
> URL: /tutorials/hosting/clone-sample-repo.html

**Comment by zenorocha** [comment]
Sorry for the inconvenience @reizero00. This should be fixed now: http://wedeploy.com//tutorials/hosting/clone-sample-repo.html (try a force reload too: cmd + shift + r)

**Comment by reizero00** [comment]
Thanks @zenorocha I was able to get through the tutorial and get a site up.

**Comment by zenorocha** [comment]
Awesome!!!
