### ISSUE TITLE
Scroll to bottom is fired when I scroll screen and the page not loaded completely

### ISSUE THREAD

**Issue by fabiorogeriosj** [wedeploy/wedeploy.com#193]
When the `docs-nav` or `CodeMirror` not binded and I start scroll, my page auto scroll to the bottom after page loaded completely, see gif:

![wedeploy4](https://user-images.githubusercontent.com/1442874/27227674-d1fe3472-527a-11e7-9bb8-7578a66e6de3.gif)

**Comment by fabiorogeriosj** [comment]
This bug happens on electricjs
https://github.com/electricjs/electric/issues/62

**Comment by jonnilundy** [comment]
Thanks for posting an issue about this, I am noticing it as well. We will get to it as soon as we can. :)

**Comment by jonathantneal** [comment]
I’m regularly replicating this bug now.

1. Begin to load the page without the Reading Time component loaded (this may require disabling cache and slowing down your connection). This does not need to be the first load of the page.

2. Before the Reading Time component loads, scroll up or down from wherever the browser puts you (as long as the position you scroll to is not the top of the page).

Related: 1. When loading the page part way down, the Reading Time component will not appear alongside the article until I have scroll back up above its top and then back down. 2. The Reading Time component jumps whenever switching to and from its fixed position.
