### ISSUE TITLE
Document how to add Liferay applications to Liferay service

### ISSUE THREAD

**Issue by mdelapenya** [wedeploy/wedeploy.com#194]
As described here: https://github.com/wedeploy/images/issues/436 and here https://github.com/wedeploy/boilerplate-liferay/issues/1

Two PR's have been sent here https://github.com/wedeploy/images/pull/437 and here https://github.com/wedeploy/boilerplate-liferay/pull/2/commits

**Comment by zenorocha** [comment]
Thanks @mdelapenya!
