### ISSUE TITLE
Publish Email Tutorial Problem 

### ISSUE THREAD

**Issue by doriel** [wedeploy/wedeploy.com#198]
> URL: /tutorials/email-web/it-works.html Hi there i am trying to send the email, and it doesn't work.

**Comment by jonnilundy** [comment]
Hey @doriel! Could you push your project to a GitHub repo (if you haven't already) and send it over to me here. I'd love to look over it so we can get you sending emails ASAP! 😉

**Comment by doriel** [comment]
@jonnilundy just did it (https://github.com/doriel/test-wedeploy-email)

**Comment by jonnilundy** [comment]
Thanks @doriel! Looks like you need to add your master token [here](https://github.com/doriel/test-wedeploy-email/blob/master/hosting/main.js#L9). 

Directly for how to do this will be near the bottom of [this page](http://wedeploy.com/tutorials/email-web/add-api-method.html) under **Add Master Token**.

Let me know if you have any questions!

**Comment by doriel** [comment]
@jonnilundy i just added the [Master Token](https://github.com/doriel/test-wedeploy-email/blob/master/hosting/main.js#L9) but it still does not work...

**Comment by jonnilundy** [comment]
Okay. Are there any errors in the console when you try to send an email?

**Comment by doriel** [comment]
@jonnilundy I don't know how but it's just working so thank you "Very Much"....

**Comment by jonnilundy** [comment]
@doriel, Helping make sure WeDeploy is working well for you is never a waste of time!! :) Glad to help. Don't hesitate to reach out if anything else goes wrong. If you want to ping me personally with questions or just see other conversations that are happening about WeDeploy, check out our [Slack Channel](http://chat.wedeploy.com/). 🎉
