### ISSUE TITLE
Tutorial Problem

### ISSUE THREAD

**Issue by awlui** [wedeploy/wedeploy.com#199]
> URL: /tutorials/nodejs/deploy-your-app.html

Pushing to git server not linking to project created on wedeploy account and building node server.

**Comment by jonnilundy** [comment]
Hey @awlui! Was there any errors when you tried to push to Git?

**Comment by awlui** [comment]
Nope no errors, I just took a look at other issues already posted and mine sound similar to issue #192 . No errors pushing to git. I also pushed to a remote repository on my account if you want to take a look, https://github.com/awlui/wedeploynode.

**Comment by awlui** [comment]
I tried the auth and email tuts as well. Those went without a hitch.

**Comment by jonnilundy** [comment]
Good news! In your `nodejs` folder, change the filename of your `container.js` to `container.json`. 👍 

Try pushing again after that and let me know if it works! :)

**Comment by awlui** [comment]
Oh jeez, don't know how I missed that, that's embarrassing hah. I just pushed it to the wedeploy git server and it looks like its building! Thanks!

**Comment by jonnilundy** [comment]
Don't even worry about it! :) Glad we could figure it out quickly for you!
