### ISSUE TITLE
Scrolling doesn't seem to be synced to the progress meter

### ISSUE THREAD

**Issue by NolanChan** [wedeploy/wedeploy.com#225]
On https://ui-wedeploy.wedeploy.io/docs/auth/manage-users, it seems that progress meter is significantly lagging behind the current place in the browser

<img width="1338" alt="screen shot 2017-08-05 at 1 36 35 pm" src="https://user-images.githubusercontent.com/1487616/28998561-1f35097a-79e3-11e7-850f-9268ba9b70e9.png">

**Comment by jonnilundy** [comment]
Interesting. Have you noticed this on other pages?

**Comment by jonnilundy** [comment]
@ygorcosta @zenorocha Could you take a look at this? I've noticed on other pages as well.

**Comment by zenorocha** [comment]
Closing, since this should be fixed on Electric.
