### ISSUE TITLE
You can't create a user

### ISSUE THREAD

**Issue by yasuflatland-lf** [wedeploy/wedeploy.com#229]
> URL: /tutorials/auth-web/it-works.html

Following steps of the document. 
https://ui-wedeploy.wedeploy.io/tutorials/auth-web/it-works.html

1. Navigate to ui-<projectID>.wedeploy.io
2. Click "Create an account"
3. Type as follows. Name -> ddd, email -> ddd@liferay.com, password -> ddd
4. You get "Sign-up failed. Try another email" error.

**Comment by jonnilundy** [comment]
Hello, Yasuyuki! Do you have this implemented on a GitHub repo that I could look at?

**Comment by yasuflatland-lf** [comment]
Hi Jonni, I've uploaded the repo here. https://github.com/yasuflatland-lf/tutorial-auth-web.

**Comment by NolanChan** [comment]
Hi @yasuflatland-lf , currently we're having some issues with our `auth` service. I believe to make it work, please change your auth/wedeploy.json to:

{
    "id": "auth",
    "image": "wedeploy/auth:0.0.1",
    "env": {
        "WEDEPLOY_AUTH_SECURE_FIELDS": "password",
        "WEDEPLOY_AUTH_PASSWORD": "true"
    }
}

**Comment by yasuflatland-lf** [comment]
Hi @NolanChan , looks like it failes and the behaviors were same... 

the wedeploy CLI version is
WeDeploy CLI version 1.0.7 darwin/amd64
Build commit: f39e3f0ccc0b3e104dd35de5750cd90006a424be
Build time: Thu Aug 10 17:23:50 UTC 2017

I also tried https://github.com/wedeploy/boilerplate-auth/tree/web as well, but I couldn't create a user or login, even with Google / Github account with it. 

While doing above action, wedeploy CLI told that I need to add ids for services, (ids were missing in wedelopoy.json files in the boilerplate-auth/tree/web) so I added and run ```we deploy -p authtestyasu```. Services seem like working and I could access the ui service. Should I create another issue on this?

**Comment by eduardolundgren** [comment]
@yasuflatland-lf Update the CLI, this should get rid of asking the ids, `we update`

**Comment by yasuflatland-lf** [comment]
Hi @eduardolundgren , I've already updated wedeploy CLI to 1.0.7 (seems like the latest version), but still asked. 

> Your service doesn't have an ID. Type one [or use: auth]

I just type return and I could deploy though.

**Comment by eduardolundgren** [comment]
@yasuflatland-lf okay, @henvic could you check what's happening?

**Comment by eduardolundgren** [comment]
@yasuflatland-lf Could you remove the lines:

```
"env": {
        "WEDEPLOY_AUTH_SECURE_FIELDS": "password",
        "WEDEPLOY_AUTH_PASSWORD": "true"
    }
```

and retest the deployment? Make sure to use the id `auth` in your service as well (it's a bug we need to fix asap).

**Comment by yasuflatland-lf** [comment]
Hi @eduardolundgren , in terms of a project created according to https://wedeploy.com/tutorials/auth-web/, I tested

1.  Delete the project and deploy as a new project
2. Tried to reset the deployment according to your advice

The result was same as follows

- If you open up ui-* page for the first time, I got an error below in the browser.

>  Uncaught TypeError: Cannot read property 'name' of null at main.js:37

- Go to "Create an account" link and tried to create a user, I got a message " Sign-in failed. Try another email/password." and couldn't create a user. I got an errors in the browser (chrome) as below 

> wedeploy.js:10 OPTIONS https://users-%3Cprojectid%3E.wedeploy.io/users 404 (Not Found)

> XMLHttpRequest cannot load https://users-%3Cprojectid%3E.wedeploy.io/users. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ui-p222.wedeploy.io' is therefore not allowed access. The response had HTTP status code 404.

**Comment by eduardolundgren** [comment]
@yasuflatland-lf I've sent you two pull requests with changes that will make it work https://github.com/yasuflatland-lf/tutorial-auth-web/pulls.

/cc @zenorocha @jonnilundy Tutorial needs an update to fix those issues.

**Comment by yasuflatland-lf** [comment]
Hi @eduardolundgren, thank you for the pull request! It worked! Sorry for bothering you. I'll try to report you guys with an actual fix if I can fix myself next time!

**Comment by eduardolundgren** [comment]
@yasuflatland-lf you are welcome!
