### ISSUE TITLE
Wordpress sample code didn't run properly

### ISSUE THREAD

**Issue by yasuflatland-lf** [wedeploy/wedeploy.com#232]
> URL: https://wedeploy.com/docs/deploy/deploying-docker/

I tried to run the sample code of Docker (https://github.com/wedeploy/demo-wordpress), it didn't run properly. I didn't change the code. The steps are as follows

1.`git clone https://github.com/wedeploy/demo-wordpress`
2. go to  /demo-wordpress folder
3. Run 'we deploy -p wptest'
4. `db`'s status turns to "online", but wp doesn't. The log is as follows.

-----

wp[build] Step 1/2 : FROM wordpress
wp[build] ---> c4260b289fc7
wp[build] Step 2/2 : LABEL com.wedeploy.container.build '238340457253077360' com.wedeploy.container.container 'wp' com.wedeploy.container.groupUid 'kylr32d' com.wedeploy.container.project 'wpt'
wp[build] ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
wp[build] ---> Running in eea2f425098b
wp[build] ---> 12515eea4ee3
wp[build] Removing intermediate container eea2f425098b
wp[build] Successfully built 12515eea4ee3
wp[build] Successfully tagged registry.private-wedeploy-prod1:5000/wedeploy-build-ex8krbt:kylr32d
wp[build] The push refers to a repository [registry.private-wedeploy-prod1:5000/wedeploy-build-ex8krbt]
wp[build] Preparing 76677c58a299
wp[build] Preparing 562dd11ed871
wp[build] Preparing 6671cb9eb6b3
wp[build] Preparing 4214911d5945
wp[build] Preparing fed26d7fe7b9
wp[build] Preparing c8c6d352c96e
wp[build] Preparing 5a151fa4136e
wp[build] Preparing 8747705a74d9
wp[build] Preparing adfd7c98cdf6
wp[build] Preparing 354b4ef9664b
wp[build] Preparing 2da371244fc1
wp[build] Preparing 315db89f9acb
wp[build] Preparing 3d2582fdede2
wp[build] Preparing 53da01089a82
wp[build] Preparing 0fd7a67d49b3
wp[build] Preparing f0c367fa8636
wp[build] Preparing ddd6dcab19ff
wp[build] Preparing 2c40c66f7667
wp[build] Mounted from wedeploy-build-h6gyyzv 3d2582fdede2
wp[build] Mounted from wedeploy-build-h6gyyzv ddd6dcab19ff
wp[build] Mounted from wedeploy-build-h6gyyzv c8c6d352c96e
wp[build] Mounted from wedeploy-build-h6gyyzv 562dd11ed871
wp[build] Mounted from wedeploy-build-h6gyyzv 53da01089a82
wp[build] Mounted from wedeploy-build-95jtx45 4214911d5945
wp[build] Mounted from wedeploy-build-h6gyyzv 2da371244fc1
wp[build] Mounted from wedeploy-build-95jtx45 76677c58a299
wp[build] Mounted from wedeploy-build-95jtx45 adfd7c98cdf6
wp[build] Mounted from wedeploy-build-95jtx45 fed26d7fe7b9
wp[build] Mounted from wedeploy-build-h6gyyzv 315db89f9acb
wp[build] Mounted from wedeploy-build-h6gyyzv 5a151fa4136e
wp[build] Mounted from wedeploy-build-h6gyyzv 2c40c66f7667
wp[build] Mounted from wedeploy-build-h6gyyzv 6671cb9eb6b3
wp[build] Mounted from wedeploy-build-h6gyyzv 8747705a74d9
wp[build] Mounted from wedeploy-build-h6gyyzv f0c367fa8636
wp[build] Mounted from wedeploy-build-h6gyyzv 0fd7a67d49b3
wp[build] Mounted from wedeploy-build-95jtx45 354b4ef9664b
wp[build] kylr32d: digest: sha256:039f3c2cc20f1cb2d49cdd76036f64bb6636eed0467f4ddf413073ab9b8ba0fc size: 4078
wp[901f37e2] WordPress not found in /var/www/html - copying now...
wp[901f37e2] Complete! WordPress has been successfully copied to /var/www/html
wp[901f37e2]
wp[901f37e2] Warning:
wp[901f37e2] MySQL Conmysqli::mysqli(): (Hnection ErY000/2002)ror: (2002: Connecti) Connection refusedon refused in - on line 22
wp[901f37e2]
wp[901f37e2] 2017/08/08 00:19:54 INFO: health check failed
wp[901f37e2]
wp[901f37e2] Wa
wp[901f37e2] MySQL Corning: mysnnection Eqli::mysqlrror: (200i(): (HY002) Connect0/2002): Cion refuseonnection d
wp[901f37e2] refused in - on line 22
wp[901f37e2] 2017/08/08 00:19:57 INFO: health check failed
wp[901f37e2]
wp[901f37e2] Warni
wp[901f37e2] MySQL Cng: mysqlionnection ::mysqli()Error: (2002) Connec: (HY000/2tion refus002): Conned
wp[901f37e2] ection refused in - on line 22
wp[901f37e2] 2017/08/08 00:20:00 INFO: health check failed
wp[901f37e2]
wp[901f37e2] Warning:
wp[901f37e2] MySQL Connection mysqli::m Error: (2ysqli(): (002) ConneHY000/2002ction refused
wp[901f37e2] ): Connection refused in - on line 22
wp[901f37e2] 2017/08/08 00:20:03 INFO: health check failed
wp[901f37e2]
wp[901f37e2] W
wp[901f37e2] MySQL Connectioarning: myn Error: (sqli::mysq2002) Connli(): (HY0ection ref00/2002): used
wp[901f37e2] Connection refused in - on line 22
wp[901f37e2] 2017/08/08 00:20:06 INFO: health check failed
wp[901f37e2]
wp[901f37e2] Warn
wp[901f37e2] MySQing: mysqlL Connectii::mysqli(on Error: ): (HY000/(2002) Connection re2002): Confused
wp[901f37e2] nection refused in - on line 22
wp[901f37e2] 2017/08/08 00:20:09 INFO: health check failed
wp[901f37e2]
wp[901f37e2] Warning
wp[901f37e2] MySQL Connect: mysqli::ion Error:mysqli(): (2002) Co(HY000/2002): Connecnnection refused
wp[901f37e2] tion refused in - on line 22
wp[901f37e2] 2017/08/08 00:20:12 INFO: health check failed
wp[901f37e2]
wp[901f37e2]
wp[901f37e2] MyWarning: mSQL Connection Errorysqli::mys: (2002) Cqli(): (HY000/2002):onnection Connectiorefused
wp[901f37e2] n refused in - on line 22
wp[901f37e2] 2017/08/08 00:20:15 INFO: health check failed
wp[901f37e2]
wp[901f37e2] War
wp[901f37e2] Mning: mysqySQL Connection Erroli::mysqlir: (2002) (): (HY000Connection/2002): Co refused
wp[901f37e2] nnection refused in - on line 22
wp[901f37e2] 2017/08/08 00:20:18 INFO: health check failed
wp[901f37e2]
wp[901f37e2] Warnin
wp[901f37e2] g: mysqli:MySQL Conn:mysqli():ection Error: (2002) (HY000/20 Connectio02): Connen refused
wp[901f37e2] ction refused in - on line 22
wp[901f37e2] 2017/08/08 00:20:18 INFO: execution terminated
wp[d9a98346] WordPress not found in /var/www/html - copying now...
wp[d9a98346] Complete! WordPress has been successfully copied to /var/www/html
wp[d9a98346] AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.95.4. Set the 'ServerName' directive globally to suppress this message
wp[d9a98346] AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.95.4. Set the 'ServerName' directive globally to suppress this message
wp[d9a98346] [Tue Aug 08 00:20:25.976145 2017] [mpm_prefork:notice] [pid 13] AH00163: Apache/2.4.10 (Debian) PHP/5.6.31 configured -- resuming normal operations
wp[d9a98346] [Tue Aug 08 00:20:25.976176 2017] [core:notice] [pid 13] AH00094: Command line: 'apache2 -D FOREGROUND'

**Comment by jonnilundy** [comment]
Hey @yasuflatland-lf, I followed the same steps that you laid out above and it seemed to work for me. 
One thing to note, we have a small bug regarding the warning for some Docker service with databases. In this case, it is showing a warning even though it succeeded. This is because the the mysql db and the wp image are deploying at the same time so the wp image can't validate the connection with the db. Again, this is just a bug in the error logs.

Here is my test here:
[wp-wptest2.wedeploy.io](https://wp-wptest2.wedeploy.io)

**Comment by yasuflatland-lf** [comment]
Hi @jonnilundy , Ok, Let me give it a try again. Yeah, I didn't check if it's visible from a browser. I will let you know how it goes!

**Comment by jonnilundy** [comment]
Cool! Yes, let me know if it works.

**Comment by yasuflatland-lf** [comment]
Yeah, it worked and super fast! Thank you for helping on this!

**Comment by jonnilundy** [comment]
Awesome! :) Glad to help. Love all your contribution.
