### ISSUE TITLE
Tutorial Problem

### ISSUE THREAD

**Issue by willianbs** [wedeploy/wedeploy.com#236]
> URL: /tutorials/liferay-dxp/it-works/

Deploying services on project testedxp in wedeploy.com...
! Upload completed in 4s
⠼ Build successful testeDXP-testedxp.wedeploy.io

**Fica em Build Successfull mas no console dá erro:**

testedxp[49564197] 2017/08/09 15:21:10 INFO: health check failed
testedxp[49564197] 2017/08/09 15:21:13 INFO: health check failed
testedxp[49564197] 2017/08/09 15:21:16 INFO: health check failed

**Comment by ricardofunke** [comment]
Olá @willianbs,

Sou Ricardo Funke. A princípio gostaria apenas de esclarecer que estas mensagens não são geradas pela aplicação Liferay, nem são relacionadas diretamente com o deploy dele no WeDeploy.

Então, provavelmente o deploy de seu Liferay DXP ocorreu com sucesso, você apenas terá que aguardar um pouco mais para que haja tempo para a aplicação subir completamente.

As mensagens "health check failed" estão ocorrendo com frequência nesse momento em qualquer deploy, se tratam de um sistema interno do WeDeploy, já estamos cientes e providenciando uma solução.

Por tanto, procure ignorar estas mensagens por enquanto.

Caso ainda esteja enfrentando problemas com este deploy do Liferay DXP depois de um tempo, por favor nos informe, anexando novamente possíveis novas mensagens caso ocorram para que possamos analisar, tudo bem?

Obrigado por utilizar o WeDeploy!
