### ISSUE TITLE
Add version tag variables for java api

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#237]
Now that we don't hard code the [image and api versions](https://github.com/wedeploy/wedeploy.com/blob/master/src/site.json) on wedeploy.com, should we add the java api? What would be a good naming system for it?

Use case is @mdelapenya's iot blogpost (#233)

cc @eduardolundgren @igr

**Comment by zenorocha** [comment]
We do have a version for Android already, but not for the Java one. https://github.com/wedeploy/wedeploy.com/blob/master/src/site.json#L8

**Comment by jonnilundy** [comment]
Are you wanting to not add a Java one?

**Comment by zenorocha** [comment]
We don't have an official Java API anymore, we need to decide what to do about it.

**Comment by mdelapenya** [comment]
If we are not going to have a Java API, how are we going to use it from Java applications?

**Comment by zenorocha** [comment]
We do need a Java API for sure. In the meantime, we should add a new tab on every code block that shows an example with curl. At least other people who doesn't know JS, Swift, Android will be able to use those APIs.

**Comment by zenorocha** [comment]
Closing since the Java SDK has not been released yet. When it's released we can add it here.
