### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by DWoonD** [wedeploy/wedeploy.com#238]
I follow the nodejs application tutorial and received this error message when i try deploy

Deploying services on project dwoond in wedeploy.com...
! Deployment failed in 1s.kage...
! Upload failed app-dwoond.wedeploy.io.
! Something went wrong with your "we deploy" operation.
! Deployment push failed.

I'm useing cli in windows 10

Edit, in wedeploy.json I use 'id': 'app' and in the cli i call we deploy -p nameproject (name the project in the site wedeploy)

If i try in the cly we deploy -p app i got this error

 Something went wrong with your "we deploy" operation.
! Access is restricted to collaborators.

**Comment by henvic** [comment]
Hi @DWoonD,
can you please do the following?

1. run `we update`
2. try `we deploy -p app-<random number>

It might be the case that the project `app` is owned by someone else and you are not a collaborator. I am going to improve the error message for this case.

**Comment by henvic** [comment]
If that doesn't help, can you please try provide the following details:

1. Output of `we version`
2. Run command with `we deploy -p app-<random number> --verbose --defer-verbose-output`

**Comment by DWoonD** [comment]
C:\Projetos\wedeploy\tutorial-nodejs>we deploy update
! Something went wrong with your "we deploy" operation.
! Invalid number of arguments: too many.

C:\Projetos\wedeploy\tutorial-nodejs>we version
WeDeploy CLI version 1.0.7 windows/amd64
Build commit: f39e3f0ccc0b3e104dd35de5750cd90006a424be
Build time: Thu Aug 10 17:23:50 UTC 2017

C:\Projetos\wedeploy\tutorial-nodejs>we deploy -p app-9998990877678323
! Something went wrong with your "we deploy" operation.
! Invalid parameter "projectId" for "app-9998990877678323".

C:\Projetos\wedeploy\tutorial-nodejs>we deploy -p app-9998990877678323 --verbose --defer-verbose-output
Defering verbose output (might lose messages on failures)
! Something went wrong with your "we deploy" operation.
! Invalid parameter "projectId" for "app-9998990877678323".

If you can wait, I'm in the corporate network and I think then this can be a problem. I will try again in my home

**Comment by zenorocha** [comment]
I think the first command was wrong: `we deploy update` is actually `we update`

**Comment by henvic** [comment]
Oops. Our projects doesn't work with "-". Try something like app27725
instead. Sorry about that.
-- 
Henrique Vicente
https://henvic.github.io/
https://github.com/henvic
http://flickr.com/photos/henriquev/

**Comment by khaueviana** [comment]
I receive this error message too:

λ  we deploy -p kvfirstapp -s app --verbose --defer-verbose-output
Defering verbose output (might lose messages on failures)
Deploying services on project kvfirstapp in wedeploy.com...
⠦ Uploading deployment package...
⠂ app-kvfirstapp.wedeploy.io
fatal: unable to access 'https://git.wedeploy.com/kvfirstapp.git/': error setting certificate verify locations:
Deploying services on project kvfirstapp in wedeploy.com...-bundle.crt
! Deployment failed in 1s.kage...
! Upload failed app-kvfirstapp.wedeploy.io.app.git
! Something went wrong with your "we deploy" operation.
! Deployment push failed.

**Comment by henvic** [comment]
@khaueviana,
Have you copied the entire message here? It appears not...

Can you please update the app with `we update` and try again with `we deploy -p kvfirstapp -s app -V`?

I added the more friendly "--defer-verbose" flag)or -V shortcut) today to make it simpler.

**Comment by henvic** [comment]
Also, what operating version and version are you using? I am afraid this seems to be an operating system misconfiguration.

**Comment by khaueviana** [comment]
We version:

> WeDeploy CLI version 1.0.9 windows/amd64
> Build commit: cb900e9e2b3f74e2a6b644b6d852326690218aae
> Build time: Fri Aug 11 05:40:05 UTC 2017

Error message like you said:

> Deploying services on project kvfirstapp in wedeploy.com...
> ⠙ Uploading deployment package...
> ⠂ app-kvfirstapp.wedeploy.io
> fatal: unable to access 'https://git.wedeploy.com/kvfirstapp.git/': error setting certificate verify locations:
> Deploying services on project kvfirstapp in wedeploy.com...-bundle.crt
> ! Deployment failed in 1s.
> ! Upload failed app-kvfirstapp.wedeploy.io.app.git
> ! Something went wrong with your "we deploy" operation.
> ! Deployment push failed.
> 
>  Deferred verbose messages below
> > GET https://api.wedeploy.com/projects/kvfirstapp HTTP/1.1
> Authorization:  1 hidden value
> User-Agent: WeDeploy/master (+https://wedeploy.com)
> Content-Type: application/json
> 
> 
> < HTTP/1.1 200 OK
> Strict-Transport-Security: max-age=15552000; includeSubDomains
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> X-Ratelimit-Remaining: 99999
> Vary: Accept-Encoding
> X-Download-Options: noopen
> Access-Control-Allow-Origin: *
> X-Ratelimit-Limit: 100000
> Content-Length: 311
> Etag: W/"137-9uZceV8YW9ioyfYa4OYEcL1imyw"
> X-Dns-Prefetch-Control: off
> Content-Type: application/json; charset=utf-8
> Date: Fri, 11 Aug 2017 12:39:25 GMT
> X-Frame-Options: SAMEORIGIN
> 
> {
>     "createdAt": 1502296097987,
>     "github": {},
>     "invitations": {},
>     "collaborators": [
>         "238643393635669819"
>     ],
>     "health": "up",
>     "healthUid": "a88ee5aa-98ca-45bb-8f04-6e89e1d7e404",
>     "planId": "free",
>     "id": "238643520211432093",
>     "masterToken": "f9379d40-3291-4350-8d16-c80028698022",
>     "ownerId": "238643393635669819",
>     "projectId": "kvfirstapp"
> }
> 
> Running git init
> Running git config user.name WeDeploy user --local
> Running git config user.email user@deployment --local
> Running git add C:\Concrete\Projetos\repo-my-own\tutorial-hosting
> Running git hash-object -w --stdin
> Using hash-object:
> {
>     "id": "app"
> }
> Running git update-index --add --cacheinfo 100644 8c8824ea21f32d502b23d79d08be020a3009d82e
>  wedeploy.json
> Running git commit --allow-empty --message Deployment at Fri Aug 11 09:39:24 -0300 2017
> Running git rev-parse HEAD
> commit eb782c26f09308e805fae85baf479d48bd4faa12
> Running git remote add wedeploy https://git.wedeploy.com/kvfirstapp.git
> Resetting credential helpers
> Running git config --add credential.helper
> Running git config --add credential.helper C:\\Users\\Khaue Viana\\AppData\\Local\\Programs\\we\\bin\\we.exe git-credential-helper
> Running git push wedeploy master --force --verbose

**Comment by khaueviana** [comment]
I'm using WIN 10 🗡

**Comment by lucasfontesgaspareto** [comment]
I got the same error and i'm using Win10 too.
```
WeDeploy CLI version 1.0.9 windows/amd64
Build commit: cb900e9e2b3f74e2a6b644b6d852326690218aae
Build time: Fri Aug 11 05:40:05 UTC 2017
```

`we deploy -p projectName -s serviceName -V`

```
Deploying services on project projectName in wedeploy.com...
⠙ Uploading deployment package...
⠂ serviceName-projectName.wedeploy.io
fatal: unable to access 'https://git.wedeploy.com/projectName.git/': error setting certificate verify locations:
Deploying services on project projectName in wedeploy.com...
! Deployment failed in 1s.
! Upload failed serviceName-projectName.wedeploy.io.
! Something went wrong with your "we deploy" operation.
! Deployment push failed.

 Deferred verbose messages below
> GET https://api.wedeploy.com/projects/projectName HTTP/1.1
User-Agent: WeDeploy/master (+https://wedeploy.com)
Content-Type: application/json
Authorization:  1 hidden value


< HTTP/1.1 200 OK
Etag: W/"131-5TAqqg/t7RK5sfD4Aw8GP+vggzs"
Date: Fri, 11 Aug 2017 20:32:34 GMT
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 100000
Content-Type: application/json; charset=utf-8
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block
Access-Control-Allow-Origin: *
X-Ratelimit-Remaining: 99977
Content-Length: 305
Vary: Accept-Encoding
X-Dns-Prefetch-Control: off

{
    "createdAt": 1502482936299,
    "github": {},
    "invitations": {},
    "collaborators": [
        "238816412022598170"
    ],
    "health": "up",
    "healthUid": "21ed7b57-84bd-4f7c-891f-ceff5bf88f96",
    "planId": "free",
    "id": "239035348546762183",
    "masterToken": "56be6639-4a59-4790-a7bd-b3143a7fa5b9",
    "ownerId": "238816412022598170",
    "projectId": "projectName"
}

Running git init
Running git config user.name WeDeploy user --local
Running git config user.email user@deployment --local
Running git add C:\****\****\****\projectName-server
Service not found. Creating service package on git repo only.
Running git hash-object -w --stdin
Using hash-object:
{
    "id": "serviceName"
}
Running git update-index --add --cacheinfo 100644 2547b2404a188c6c15477be78b344006fdc00f9b
 wedeploy.json
Running git commit --allow-empty --message Deployment at Fri Aug 11 17:33:09 -0300 2017
Running git rev-parse HEAD
commit 364969ddd4dd44fd334751dff8079c322597f5f0
Running git remote add wedeploy https://git.wedeploy.com/projectName.git
Resetting credential helpers
Running git config --add credential.helper
Running git config --add credential.helper C:\\****\\****\\AppData\\Local\\Programs\\we\\bin\\we.exe git-credential-helper
Running git push wedeploy master --force --verbose
```

**Comment by henvic** [comment]
Hi guys,
I am sorry for the trouble you have been through.

I am able to reproduce your errors now. Working on a solution. Hang tight.

**Comment by henvic** [comment]
Can you please provide me the output of `git config --system http.sslCAInfo`?

**Comment by lucasfontesgaspareto** [comment]
@henvic `C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt`

**Comment by henvic** [comment]
I think I solved this. @lucasfontesgaspareto, @khaueviana, @DWoonD can you please test?

If you want an explanation of my findings, keep reading on:
However, the way I did it is very, very, very strange though and may cause other problems for other users (of Windows)... Basically I add a `GIT_CONFIG_NOSYSTEM=true` environment variable on non-Windows systems, but stopped doing so on Windows.

```go
switch runtime.GOOS {
	case "windows":
		verbose.Debug("Microsoft Windows detected: using git system config")
	default:
		envs["GIT_CONFIG_NOSYSTEM"] = "true"
	}
```

Two days ago I made a change to add it on all systems, however some people started to complain they had broken git system configs (and I bet most of them are people who pushes from a GUI such as GitHub for Desktop or Sourcetree, though I know for fact that at least some uses the terminal for that as well).

So, I have tried to use the `GIT_SSL_CAINFO` environment variable (see https://github.com/git/git/blob/8b2efe2a0fd93b8721879f796d848a9ce785647f/Documentation/config.txt#L1941) to fix this on Windows, but somehow it seemed to ignore... And actually I found nothing so relevant on the Windows' system git config found on the system git config... So it might even be an issue on git itself (the second one I find, if this the case).

**Comment by DWoonD** [comment]
I test in my home now and i just update and use the command -p nameproject -s nameservice and it build and work.

thanks guys

**Comment by lucasfontesgaspareto** [comment]
Working fine bro!
```
WeDeploy CLI version 1.0.10 windows/amd64
Build commit: 8656e89d3b6d6ae4c578d9738f87674babf28b31
Build time: Sat Aug 12 03:39:06 UTC 2017
```

Thanks @henvic and others!

**Comment by henvic** [comment]
Thank you, guys.

**Comment by khaueviana** [comment]
Now I got this error:

> Deploying services on project kvfirstapp in wedeploy.com...
> ⠦ Uploading deployment package...
> ⠂ app-kvfirstapp.wedeploy.io
> Deploying services on project kvfirstapp in wedeploy.com...we.exe git-credential-helper get: C:\Users\Khaue: No such file or directory
> ! Deployment failed in 2s.name for 'https://git.wedeploy.com': terminal prompts disabled
> ! Upload failed app-kvfirstapp.wedeploy.io.app.git
> ! Something went wrong with your "we deploy" operation.
> ! Invalid credentials.

**Comment by henvic** [comment]
**(Anyone who needs help with the CLI tool)**, it always help if you provide the following:

```bash
# It is important for me to know what version you are running
$ we version

# result of the command with verbose output (please include the command called as well)
$ we <cmd> [flags] -v

# for commands that update things in-line, use deferred verbose:
$ we <cmd> [flags] -V

# for example
$ we deploy --service bar -V 
```

**Comment by henvic** [comment]
@khaueviana, can you please try to provide that? Thanks.

**Comment by khaueviana** [comment]
Do you think is something in my machine? 

> ⚡ Khaue Viana@CS  C\..\..\..\tutorial-hosting   master ≣ +1 ~0 -0 !   we version
> WeDeploy CLI version 1.0.10 windows/amd64
> Build commit: 8656e89d3b6d6ae4c578d9738f87674babf28b31
> Build time: Sat Aug 12 03:39:06 UTC 2017
>  ⚡ Khaue Viana@CS  C\..\..\..\tutorial-hosting   master ≣ +1 ~0 -0 !  we update
> ! Channel "stable" is now selected.
> ! Current installed version is 1.0.10
> ! No updates available.
>  ⚡ Khaue Viana@CS  C\..\..\..\tutorial-hosting   master ≣ +1 ~0 -0 !  we deploy -p kvfirstapp -s app1 -V
> Deploying services on project kvfirstapp in wedeploy.com...
> ⠧ Uploading deployment package...
> ⠂ app1-kvfirstapp.wedeploy.io
> Deploying services on project kvfirstapp in wedeploy.com...we.exe git-credential-helper get: C:\Users\Khaue: No such file or directory
> ! Deployment failed in 2s.kage...r 'https://git.wedeploy.com': terminal prompts disabled
> ! Upload failed app1-kvfirstapp.wedeploy.io.pp.git
> ! Something went wrong with your "we deploy" operation.
> ! Invalid credentials.
> 
>  Deferred verbose messages below
> > GET https://api.wedeploy.com/projects/kvfirstapp HTTP/1.1
> User-Agent: WeDeploy/master (+https://wedeploy.com)
> Content-Type: application/json
> Authorization:  1 hidden value
> 
> 
> < HTTP/1.1 200 OK
> Content-Length: 311
> Etag: W/"137-IUeV6ositYGbOBgI+Fbq6c855rw"
> X-Dns-Prefetch-Control: off
> X-Frame-Options: SAMEORIGIN
> Access-Control-Allow-Origin: *
> X-Ratelimit-Remaining: 99998
> Strict-Transport-Security: max-age=15552000; includeSubDomains
> X-Download-Options: noopen
> Date: Mon, 14 Aug 2017 17:08:03 GMT
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> X-Ratelimit-Limit: 100000
> Content-Type: application/json; charset=utf-8
> Vary: Accept-Encoding
> 
> {
>     "createdAt": 1502296097987,
>     "github": {},
>     "invitations": {},
>     "collaborators": [
>         "238643393635669819"
>     ],
>     "health": "up",
>     "healthUid": "fa430e4a-c452-4479-b0c8-a6222e43d650",
>     "planId": "free",
>     "id": "238643520211432093",
>     "masterToken": "f9379d40-3291-4350-8d16-c80028698022",
>     "ownerId": "238643393635669819",
>     "projectId": "kvfirstapp"
> }
> 
> Running git init
> Microsoft Windows detected: using git system config
> Running git config user.name WeDeploy user --local
> Running git config user.email user@deployment --local
> Running git add C:\Concrete\Projetos\repo-my-own\tutorial-hosting
> Running git hash-object -w --stdin
> Using hash-object:
> {
>     "id": "app1"
> }
> Running git update-index --add --cacheinfo 100644 92f5147f76463388f0c7520beea27253068e2608
>  wedeploy.json
> Running git commit --allow-empty --message Deployment at Mon Aug 14 14:08:00 -0300 2017
> Running git rev-parse HEAD
> commit 7a5a47481bf4059018db5f4f25161d4ef6ba546b
> Running git remote add wedeploy https://git.wedeploy.com/kvfirstapp.git
> Resetting credential helpers
> Running git config --add credential.helper
> Running git config --add credential.helper C:\\Users\\Khaue Viana\\AppData\\Local\\Programs\\we\\bin\\we.exe git-credential-helper
> Running git push wedeploy master --force --verbose

**Comment by henvic** [comment]
What terminal program are you using, @khaueviana?

**Comment by jonnilundy** [comment]
@khaueviana is this issue still happening to you? If so, @henvic would love to continue trouble shooting with you. If not, we will close this issue.

**Comment by phqueiroz** [comment]
I have the same problem. I'm using git bash but i tried windows 10 command prompt too.

> $ we version
WeDeploy CLI version 1.0.17 windows/amd64
Build commit: 826672e733d58a8b871e798aacb26b2af635c666
Build time: Wed Aug 30 00:31:56 UTC 2017

> $ we deploy -p randomproject -V
Deploying services on project randomproject in wedeploy.com...
⠧ Uploading deployment package...
⠂ appwedeploy-randomproject.wedeploy.io
C:\\Users\\Phillipe Queiroz\\AppData\\Local\\Programs\\we\\bin\\we.exe git-credential-helper get: C:Deploying services on project randomproject in wedeploy.com...
! Deployment failed in 3s.
! Upload failed appwedeploy-randomproject.wedeploy.io.
! Something went wrong with your "we deploy" operation.
! Invalid credentials. <br />
Deferred verbose messages below
GET https://api.wedeploy.com/projects/randomproject HTTP/1.1
Authorization:  1 hidden value
User-Agent: WeDeploy/master (+https://wedeploy.com)
Content-Type: application/json <br/><br/>
< HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
X-Dns-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Wed, 13 Sep 2017 01:23:21 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains
Content-Type: application/json; charset=utf-8
Content-Length: 317
Etag: W/"13d-B0jgDgzd+z4QdftVkWWcly5tb0w"
Vary: Accept-Encoding <br/>
{
    "createdAt": 1505263420481,
    "github": {},
    "invitations": {},
    "collaborators": [
        "242800778467850735"
    ],
    "health": "empty",
    "healthUid": "0e47ca6e-2181-46fd-ab00-e46b79f15ace",
    "planId": "free",
    "id": "244866446507648793",
    "masterToken": "a264e3d6-43bf-4e43-8834-6f07d317d456",
    "ownerId": "242800778467850735",
    "projectId": "randomproject"
} <br/>
Running git init
Microsoft Windows detected: using git system config
Running git config user.name WeDeploy user --local
Running git config user.email user@deployment --local
Running git add C:\Users\Phillipe Queiroz\code\tutorial-hosting
Running git commit --allow-empty --message Deployment at Tue Sep 12 22:23:22 -0300 2017
Running git rev-parse HEAD
commit d03d5e00b365a8985649db5a0be721a2a5c33d9d
Running git remote add wedeploy https://git.wedeploy.com/randomproject.git
Resetting credential helpers
Running git config --add credential.helper
Running git config --add credential.helper C:\\Users\\Phillipe Queiroz\\AppData\\Local\\Programs\\we\\bin\\we.exe git-credential-helper
Running git push wedeploy master --force --verbose

> $ we update
! Channel "unstable" is now selected.
! Current installed version is 1.0.17
! No updates available.

**Comment by khaueviana** [comment]
For now I'm not using. You can close :)

**Comment by ehammo** [comment]
I got the same problem. Windows 10 here too.

`C:\Users\Pedro Sereno\AppData\Local\Programs\we\bin\we.exe git-credential-helper get: C:UsersPedro: command not found
fatal: could not read Username for 'https://git.wedeploy.com': terminal prompts disabled
Pushing to https://git.wedeploy.com/chatbot.git
! Something went wrong with your "we deploy" operation.
! Invalid credentials.

 Deferred verbose messages below
> GET https://api.wedeploy.com/projects/chatbot HTTP/1.1
User-Agent: WeDeploy/master (+https://wedeploy.com)
Content-Type: application/json
Authorization:  1 hidden value


< HTTP/1.1 200 OK
Date: Wed, 13 Sep 2017 20:27:37 GMT
X-Download-Options: noopen
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Content-Length: 311
Etag: W/"137-ACzUFt0V4phEnrEUG1Z8R+cVDuE"
Vary: Accept-Encoding
X-Dns-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Xss-Protection: 1; mode=block
Access-Control-Allow-Origin: *

{
    "createdAt": 1505334349511,
    "github": {},
    "invitations": {},
    "collaborators": [
        "245011778239569142"
    ],
    "health": "empty",
    "healthUid": "8ed52eae-5d06-4d75-9bd8-3f4cd6fa11d7",
    "planId": "free",
    "id": "245015195467014223",
    "masterToken": "dfb58f67-b32b-4fe4-8b6e-36e95e78a72b",
    "ownerId": "245011778239569142",
    "projectId": "chatbot"
}

Running git init
Microsoft Windows detected: using git system config
Running git config user.name WeDeploy user --local
Running git config user.email user@deployment --local
Running git add C:\Users\Pedro Sereno\workspace\demo-nodejs
Running git commit --allow-empty --message Deployment at Wed Sep 13 17:27:41 -0300 2017
Running git rev-parse HEAD
commit 4d73e5ccec7131a8542f2db997411c91e259e201
Running git remote add wedeploy https://git.wedeploy.com/chatbot.git
Resetting credential helpers
Running git config --add credential.helper
Running git config --add credential.helper C:\\Users\\Pedro Sereno\\AppData\\Local\\Programs\\we\\bin\\we.exe git-credential-helper
Running git push wedeploy master --force --verbose`

**Comment by MohanaRanjan** [comment]
I am getting the Invalid credentials error
I am using windows 7 and try to do the deployment in the https://wedeploy.com/tutorials/nodejs/deploy-project/
 but not succeeded. Also, i noted the highlighted comment below "Running git config --add credential.helper" in the log file below has invalid windows path 

I wonder if this post from MSDN is related to our problem

https://social.msdn.microsoft.com/Forums/en-US/accf32eb-9471-4026-a679-96175080a78a/folder-or-file-location-slash-or-?forum=netfxcompact
**we version**

WeDeploy CLI version 1.1.1 windows/386
Build commit: 982ab780781d8220f9d2cb35d42ae7ad50f91990
Build time: Wed Sep 20 00:05:19 UTC 2017


**we deploy -p testweb --verbose --defer-verbose-output**

Deploying services on project testweb in wedeploy.com...
? Uploading deployment package...
? app-testweb.wedeploy.io
C:\Users\Chennaiwallpainting\AppData\Local\Programs\we\bin\we.exe git-credential
-helper get:##  **C:UsersChennaiwallpaintingAppDataLocalProgramswebinwe.exe:** command
not found
Deploying services on project testweb in wedeploy.com....com': terminal prompts
! Deployment failed in 3s.kage...
! Upload failed app-testweb.wedeploy.io.web.git
! Something went wrong with your "we deploy" operation.
! Invalid credentials.

 Deferred verbose messages below
> GET https://api.wedeploy.com/projects/testweb HTTP/1.1
User-Agent: WeDeploy/2.0.1 (+https://wedeploy.com)
Content-Type: application/json
Authorization:  1 hidden value


< HTTP/1.1 200 OK
X-Download-Options: noopen
Content-Length: 311
Etag: W/"137-Q5vjAoOLEWmDwlONyzA9MvR51YI"
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Vary: Accept-Encoding
X-Dns-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Thu, 28 Sep 2017 11:16:33 GMT

{
    "createdAt": 1506595984359,
    "github": {},
    "invitations": {},
    "collaborators": [
        "247619028404456651"
    ],
    "health": "empty",
    "healthUid": "342bfe41-e447-472f-b778-2f17317d3d31",
    "planId": "free",
    "id": "247661035506086623",
    "masterToken": "49b84c97-2e0e-4ee9-80f6-723edd7384ac",
    "ownerId": "247619028404456651",
    "projectId": "testweb"
}

Running git init
Microsoft Windows detected: using git system config
Running git config core.autocrlf false --local
Running git config user.name WeDeploy user --local
Running git config user.email user@deployment --local
Running git add C:\Users\Chennaiwallpainting\OneDrive\Personal\Work\Development\
LiveChat\tutorial-nodejs
Running git commit --allow-empty --message Deployment at Thu Sep 28 16:45:50 +05
30 2017
Running git rev-parse HEAD
commit 4eb7458489d68c5768891cca4036043ae5409bd2
Running git remote add wedeploy https://git.wedeploy.com/testweb.git
Resetting credential helpers
Running git config --add credential.helper
Running git config --add credential.helper **C:\\Users\\Chennaiwallpainting\\AppDa
ta\\Local\\Programs\\we\\bin\\we.exe git**-credential-helper
Running git push wedeploy master --force --verbose

**Comment by henvic** [comment]
Hi everyone,

do you still have any issue deploying?

If you have the "! Invalid credentials." error, please update your git installation and it should work.
I am working on patching the CLI to make it work with really old versions of git (this issue seems to have affected only Windows users, by the way; though I was able to reproduce on Linux by using a 3-year old machine).

If it doesn't, please let me know the error.

**Comment by jonnilundy** [comment]
Hello all! I am closing this issue since we have addressed all the bugs in recent releases. Please don't hesitate to reach out to our customer service team from the WeDeploy landing page if you need further assistance.
