### ISSUE TITLE
Tutorial Problem

### ISSUE THREAD

**Issue by rodrigo-brito** [wedeploy/wedeploy.com#241]
> URL: /tutorials/nodejs/deploy-project/

When I try deploy my project, a error is returned. But without datails or more information. I use the empty project with the default `wedeploy.json`.
```
Deployment failed in 3s.
! Upload failed app-rodrigo.wedeploy.io.
! Something went wrong with your "we deploy" operation.
!  500.
```

**Comment by jonnilundy** [comment]
@rodrigo-brito, sorry for the delayed response. Would you be able to try the deployment one more time and let me know if there was an error?

**Comment by jonnilundy** [comment]
@rodrigo-brito because of inactivity, I am going to close this issue. Don't hesitate to reach out to our customer service team from the WeDeploy main page if you need further assistance.

**Comment by rodrigo-brito** [comment]
Sorry! I don't saw your response. The problem was solved some days later, I think that could be a temporary behaviour from server.
