### ISSUE TITLE
Tutorial Problem DXP sample not working

### ISSUE THREAD

**Issue by guillermogutierrez** [wedeploy/wedeploy.com#242]
> URL: /tutorials/liferay-dxp/it-works/

This error is thrown when trying to start the DXP portal following the tutorial steps

app[ac745495] Deploy directory found.
app[ac745495] The following contents are going to be synchronized
app[ac745495] with Liferay:
app[ac745495]
app[ac745495] ./deploy
app[ac745495] ├── activation-key-digitalenterprisedevelopment-7.0-liferaycom.xml
app[ac745495] └── com.liferay.wedeploy.samples.portlet-1.0.0.jar
app[ac745495]
app[ac745495] 0 directories, 2 files
app[ac745495] cp: target ‘/opt/liferay/deploy’ is not a directory
app[ac745495] 2017/08/14 09:16:25 INFO: execution terminated

**Comment by zenorocha** [comment]
Hey @guillermogutierrez, could you share the ID of your app so I can debug it? I'm not sure if this is the problem, but in general it takes a long time to initialize Liferay DXP. Try accessing the URL now to see if it's already up.

**Comment by guillermogutierrez** [comment]
Hi @zenorocha 

The error was thrown in the portal logs, and after several tries, the start process was stopped. I deleted the project and recreated it and worked fine, so maybe during the building process some directories weren't properly created.

**Comment by jonnilundy** [comment]
Hey @guillermogutierrez, in like of our recent releases, DXP deployments should be much more stable. I will close this issue because I believe the issues you were facing were related to the release. Please don't hesitate to contact our customer service on the homepage if you need more support!
