### ISSUE TITLE
Document `osgi-configs` folder for Liferay DXP service

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/wedeploy.com#246]

**Comment by mdelapenya** [comment]
I've a pending PR with that ;)

**Comment by jonnilundy** [comment]
@mdelapenya are you referring to #197?

**Comment by mdelapenya** [comment]
Hey, no, it's still local. I'll try to send it today

**Comment by jonnilundy** [comment]
@mdelapenya Were you able to send over a pr for this?

**Comment by mdelapenya** [comment]
This has been merged here: https://github.com/wedeploy/wedeploy.com/pull/247

Here it is the content: https://github.com/wedeploy/wedeploy.com/blob/master/node/electric/src/pages/docs/deploy/deploying-liferay-dxp/index.md#osgi-configurations
