### ISSUE TITLE
Java Tutorial Deployment failed in Windows

### ISSUE THREAD

**Issue by flarroca** [wedeploy/wedeploy.com#248]
> URL: /tutorials/java/deploy-project/

Deployment failed in 2s.kage... Something went wrong ... Invalid credentials.

```
C:\wedeploy\tutorial-java>we login
? WeDeploy requires your browser for authenticating. Open your browser and authenticate? [A/B]
A Open Browser
B Cancel
> A
! Authentication completed in 8s [2/2]er [1/2]
! You're logged in as "*******" on "wedeploy.com".
! Check out some useful commands in case you wanna start learning the CLI:
  Command         Description
  we         Show list of all commands available in WeDeploy CLI
  we docs    Open docs on your browser
! Type a command and press Enter to execute it.

C:\wedeploy\tutorial-java>we deploy -p *****
Deploying services on project proxy in wedeploy.com...
! Deployment failed in 2s.kage...
! Upload failed app-****.wedeploy.io.
! Something went wrong with your "we deploy" operation.
! Invalid credentials.
```
I also try reproduce with vagrant/ubuntu, but cannot login without desktop interface, estrange things happens within xwpe.

**Comment by henvic** [comment]
Hi @flarroca,

What happens if you try `we list -p proxy`. Maybe someone else is already using this project id and this is why you see this error (I should improve the error message on this case, but would like your feedback first).

What happens if you try `we deploy -V`?

What version are you using?

Thanks.

**Comment by flarroca** [comment]
It Works! in a updated Ubuntu VM, with a desktop interface, to launch a browser, to complete login. I did not try again in Windows. Thanks again
