### ISSUE TITLE
Tutorial Problem

### ISSUE THREAD

**Issue by ricardofunke** [wedeploy/wedeploy.com#251]
> URL: /tutorials/auth-web/deploy-project/

Today the auth tutorial is not being deployed. It looks like it freezes when running "we deploy -p auth"

![auth-tutorial](https://user-images.githubusercontent.com/670161/30126613-465b70c6-92f1-11e7-89f4-db6e4d407985.png)

In the logs I could see some WARN messages related to network interfaces:
```
auth[7f551418] [2017-09-06 17:41:48,600] WARN [vert.x-eventloop-thread-1] i.n.u.i.MacAddressUtil#warn:136 - Failed to find a usable hardware address from the network interfaces; using random bytes: 8a:e1:c5:5f:70:37:e0:70
```

And an error, although I think this one is not related as I could see the same in other projects:
```
auth[750f2c30] 2017/09/06 17:41:56 ERROR: Termination signal SIGTERM|SIGINT received.
```

When I try to access the URL `https://auth-auth.wedeploy.io/`, I get this json:
```
{
	"code": 404,
	"message": "Not Found",
	"errors": [
		{
			"reason": "notFound",
			"message": "The requested operation failed because a resource associated with the request could not be found."
		}
	]
}
```

Full Logs attached:
[auth-tutorial.txt](https://github.com/wedeploy/wedeploy.com/files/1282141/auth-tutorial.txt)

**Comment by jonnilundy** [comment]
@ricardofunke Is this issue still persisting or was it resolved by previous releases? If it is resolved, go ahead and close the issue. Thanks!
