### ISSUE TITLE
Tutorials: It's not clear that each tutorial should have its own project

### ISSUE THREAD

**Issue by ricardofunke** [wedeploy/wedeploy.com#253]
When following the practical tutorials, it's not clear whether it should be made in different projects, so I started making all of them in the same project until I realised that some services like "ui" were being overwritten in the subsequent tutorials deployments.

Perhaps the docs should inform the user that he must create a new project or instead, make unique service names for each tutorial.

**Comment by jonnilundy** [comment]
Maybe we chould change this text to something like this:

"Note: make sure to replace projectID with the ID that you'd like for **this** project."

<img width="720" alt="screen shot 2017-09-29 at 11 14 17 am" src="https://user-images.githubusercontent.com/23219848/31029675-810849a6-a507-11e7-9a82-28a3a6cc998a.png">

**Comment by ricardofunke** [comment]
Hmm, I don't know... it looks like it wouldn't be enough for one to see that he can't make all the tutorials in the same project.

**Comment by jonnilundy** [comment]
I'm wondering if this is more of an edge case. You ran into the issue because you were doing multiple tutorials sequentially. My assumption is that most users will be doing just one tutorial. Would you agree?

**Comment by ricardofunke** [comment]
Yeah, I could agree that it could be an edge case, but I think we could easily avoid these edge cases to happen again.

I have some suggestions, we could apply only one or more than one, whatever:

1. In each tutorial we suggest a project name instead of always "projectID". For example:
```
we deploy -p myauthproject
```
2. Use unique service names, like "authui", "dataui", etc.

3. Inform the user that if he already have services with the same name in the project, it will be overwritten

But, it's only based on my impressions of what happened during my tests.

**Comment by zenorocha** [comment]
Thanks @ricardofunke, we'll think of a better solution for this. Closing for now
