### ISSUE TITLE
There is no way out from the tutorial

### ISSUE THREAD

**Issue by igr** [wedeploy/wedeploy.com#256]
For example, if you get to this page:

https://wedeploy.com/tutorials/java/it-works/

there is no link to go to home or docs home...

**Comment by jonnilundy** [comment]
Ya, they need to have a way out of tutorial captivity once they complete their journey.

**Comment by igr** [comment]
Not only on the last page, but anytime in between.

**Comment by zenorocha** [comment]
@vitorfernandes

**Comment by zenorocha** [comment]
Closing now that this is going to be redesigned on https://github.com/wedeploy/wedeploy.com/issues/256
