### ISSUE TITLE
Note users after the login that they can close the window

### ISSUE THREAD

**Issue by igr** [wedeploy/wedeploy.com#257]
Notify users that they can close the window, after the login.
One might think that the browser is still necessary, especially if he was already authenticated.

**Comment by jonnilundy** [comment]
@igr Could you move this over to the wedeploy/cli repo?

**Comment by igr** [comment]
@jonnilundy I was thinking about the web page that appears after the login.

**Comment by jonnilundy** [comment]
Are you logging in from the CLI? or what page are you referring to?

**Comment by igr** [comment]
The use case:

+ login from CLI
+ browser opens
+ user logins
+ then page appears saying everything is ok.

I was thinking about that last page - not a big deal anyway. Just if you add a sentence saying that this tab can be closed, might be nice.

**Comment by jonnilundy** [comment]
I totally agree @igr! 
@henvic is this page within the CLI repo?

**Comment by henvic** [comment]
@jonnilundy,

It is on the console repo.

I'd add a text message "You can close this window now" below the two buttons. What do you think?

**Comment by jonnilundy** [comment]
Yes, that's great! Thanks, @henvic!

**Comment by zenorocha** [comment]
Closing since it doesn't belong to the wedeploy.com repo.
