### ISSUE TITLE
Different statuses while changing the Services tabs.

### ISSUE THREAD

**Issue by igr** [wedeploy/wedeploy.com#260]
My application is not deployed for some reason. The status shown on the main page is 'Unknown'.

+ When I go to 'Services' and choose my service, the Log page appears. It shows 'Unknown' status.
+ If I go to 'Metrics' - the status is the same, 'Unknown'.
+ However, when I go to last two tabs, the status is 'Online', which is different.
+ When I go back to first two tabs, the status goes back to 'Unknown'.

Now, the real status is "Online" (since app is up). However, regardless the real state, something is wrong here, since the information is not consistent across the tabs: it should be all Unknown or Online.

**Comment by eduardolundgren** [comment]
Thanks for reporting, it seems to be an issue on console. Could you move the issue to there? Thanks

**Comment by igr** [comment]
https://github.com/wedeploy/console/issues/310
