### ISSUE TITLE
WordPress tutorial doesn't include an `image`

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/wedeploy.com#278]
Hey,

it looks like in the `wordpress` tutorial there's an `image` field missing in the `wedeploy.json`. 

Could you take a look at it @jonnilundy ? 

Thx!

**Comment by jonnilundy** [comment]
@cirocosta Which tutorial are you referring to? 

I checked [the WordPress demo](https://github.com/wedeploy/demo-wordpress) and they all had images

**Comment by cirocosta** [comment]
ah, I was thinking about a `tutorials` page in `wedeploy.com`, I think I misunderstood something then 🤔
