### ISSUE TITLE
Responsive issue in front page

### ISSUE THREAD

**Issue by ricardofunke** [wedeploy/wedeploy.com#291]
This issue was reported by a user, but I couldn't reproduce it on my phone

![img_4152](https://user-images.githubusercontent.com/670161/31280191-f2479228-aa81-11e7-9266-c86b72b7cffa.PNG)

**Comment by jonathantneal** [comment]
Notes: This appears to be a screenshot from an Android device, visiting a link from Facebook, at 375x667 (2x) in portrait (9:16). Based on the crop, it looks like either this graphic or something elsewhere on the site is kicking in a horizontal scroll.

I also could not recreate this bug, but I will look into it further.

**Comment by zenorocha** [comment]
Can we close this @jonathantneal?

**Comment by jonathantneal** [comment]
Yes. That section was updated. However, I just want to leave a note that I was unable to replicate the issue :/
