### ISSUE TITLE
Update nav link styling of old pages

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#292]
## New landing page
<img width="641" alt="screen shot 2017-10-06 at 10 40 36 am" src="https://user-images.githubusercontent.com/23219848/31290859-db674f02-aa82-11e7-98d3-bbf3c3849e51.png">

## Docs and Blog pages
<img width="635" alt="screen shot 2017-10-06 at 10 40 49 am" src="https://user-images.githubusercontent.com/23219848/31290858-db41c656-aa82-11e7-9615-90a67c140570.png">

**Comment by jonathantneal** [comment]
Thanks, @jonnilundy for getting this on the GitHub track. 😄 If possible, I’d love to update all of these with the new responsive styles coming from @vitorfernandes; Vitor, could we do that?

**Comment by jonnilundy** [comment]
@jonathantneal Yes, let's sync them in every way!

**Comment by jonathantneal** [comment]
This will be resolved by https://github.com/wedeploy/wedeploy.com/issues/355

**Comment by jonathantneal** [comment]
While #335 remains open, the items are now the same and the design is now very similar between these sections of the site.

**Comment by jonnilundy** [comment]
@jonathantneal I think I will go ahead and close since it seems like the issues still be resolved in #335 aren't related to this issue anymore. 👍
