### ISSUE TITLE
Tutorial Problem

### ISSUE THREAD

**Issue by fabianosandi** [wedeploy/wedeploy.com#294]
> URL: /tutorials/nodejs/deploy-project/

When trying to deploy the tutorial sample I get the error:

``! Deployment failed in 2s.kage...``
``! Upload failed app-intranetnlphd.wedeploy.io.``
``! Something went wrong with your "we deploy" operation.``
``! Invalid credentials.``

I'm correctly logged in the browser I algo tried using the no-browser option:

`` we login --no-browser ``

It' been 4 days with the same error

**Comment by ricardofunke** [comment]
Hi @fabianosandi,

Sorry for the inconvenience, we are already aware of this issue, it happens with some Windows users, but we couldn't reproduce it yet, suggesting that some specific user settings may be involved.

Despite it, we are giving our best in our investigations on it and we hope that soon we will be able to provide a new CLI version for Windows with this issue finally fixed.

Our apologies again for the inconvenience.

Best regards

**Comment by ricardofunke** [comment]
Hi again @fabianosandi ,

I wanted to suggest you a workaround. If you use github, you can deploy your app just by a commit to your github repository.

Follow the instructions in the link bellow to enable the Continuous Deployment in WeDeploy, it's very easy:

https://wedeploy.com/docs/deploy/continuous-deployment/ 

Best,

**Comment by sorin-pop** [comment]
I'm encountering this problem as well.

**Comment by jonnilundy** [comment]
This issue has been solved in a recent release. Thank you for reporting!
