### ISSUE TITLE
Tutorial Problem

### ISSUE THREAD

**Issue by 6ril06** [wedeploy/wedeploy.com#308]
> URL: /tutorials/docker/deploy-project/

Hi, I'm triying to deploy a docker file for MySQL following the tutorial but I have this error :

```
Running git init
Preparing deployment for project myproject in wedeploy...
⠙ Uploading deployment package...
⠂ db-myproject.wedeploy.io
Deploying services on project myproject in wedeploy.com...
! Deployment failed in 1s.
! Upload failed db-myproject.wedeploy.io.
! Something went wrong with your "we deploy" operation.
! Exit status 69.
```

Any ideas ?

**Comment by henvic** [comment]
Hi @6ril06,
can you please try again with `we deploy -v -q` and let us know what happens?

Please remove any line with "masterToken" before posting it here. Thanks!

**Comment by henvic** [comment]
@6ril06, actually... Do you happen to use macOS and just updated your system?

If so, try running 'git' or see this:
https://mythinkpond.com/2015/09/24/solved-git-status-failed-with-code-69-error-when-opening-sourcetree-in-mac-os-x/

**Comment by 6ril06** [comment]
Absolutly, I'm on a mac.
I'll try your solution this evening and post a feedback after that.

**Comment by 6ril06** [comment]
It  works fine !!
Thanks @henvic !

**Comment by henvic** [comment]
@6ril06, can you please let me know if it was macOS update related?
