### ISSUE TITLE
"The invitation link is invalid or expired" shown to user as JSON

### ISSUE THREAD

**Issue by lionah** [wedeploy/wedeploy.com#313]
Following a dead invitation link shows the user JSON instead of a web page.

```
{"status":400,"message":"Bad Request","errors":[{"reason":"invalidInvitationLink","context":{"message":"The invitation link is invalid or expired."}}]}
```

To try for yourself, click on the following bad link:

* https://api.wedeploy.com/projects/bar/invite?email=bar@example.com&invitationToken=foo

**Comment by zenorocha** [comment]
We definitely need to improve the user feedback there. I'm closing this issue here in order to move it to the appropriate repo, ok? Thanks for reporting @lionah!

**Comment by lionah** [comment]
No problem thanks!
