### ISSUE TITLE
Invalid credentials on WIN10

### ISSUE THREAD

**Issue by madhusudan1** [wedeploy/wedeploy.com#315]
> URL: /tutorials/lsna/deploy-static-files/

? Your service doesn't have an ID. Type one [or use: wedeploy]
> wedeploy
Deploying services on project msachatapp in wedeploy.com...
! Deployment failed in 2s.kage...
! Upload failed wedeploy-msachatapp.wedeploy.io.
! Something went wrong with your "we deploy" operation.
! Invalid credentials.

**Comment by henvic** [comment]
Hi @madhusudan1,

We are aware of this problem and I am working on a definitive solution for it.

Can you please try the unstable releases channel to see if it works?
`we update --channel unstable`

Then deploy it again with `we deploy`.

To go back to the stable channel, please use `we update --channel stable`.

Thanks.

**Comment by yasuflatland-lf** [comment]
Hi @henvic 

I also run into the same issue and the workaround above didn't work as of now.

I used 
'''
we update --channel unstable
'''
and it got updated, but still got same errors.

**Comment by jonnilundy** [comment]
@madhusudan1 If the issue persists, another workaround is to deploy using out GitHub webhook. Simply Go to Deploy, Github, and then authorize the branch that you would like to deploy.

**Comment by henvic** [comment]
@yasuflatland-lf,
can you please tell me what git version you are currently using?

`git -v`

If you are running git < 2.13 can you please update it and let me know if this still happens? You can head to git-scm.com to upgrade.

After you upgrade, please run

`git -v`

again to compare versions. You might have more than one git installation on your system.

**Comment by yasuflatland-lf** [comment]
@henvic ,
The version of git on my windows 10 is 2.13.0.windows.1.

@jonnilundy 
The workaround worked perfect for me as it doesn't bridge windows. But the statuses on Wedeploy console are kind wired. 

- Deployed 3 services, db, app and ui, the status on the dashboard always remains "waiting" and in overview, sometimes db and app remains warning. (sometimes it turns to online.). I refreshed the browser in 5 mins but the results were same.

- After connecting the project to the Github repository and click "redeploy", the pop ups appear on the bottom, but the "Logs" link in the one of pop ups didn't work. (This is minor. I can click on Logs of dashboard page)

**Comment by jonnilundy** [comment]
@henvic @yasuflatland-lf @madhusudan1 I am closing this issue because I believe it has been solved with recent releases. Please feel free to reopen if your issue persists.
