### ISSUE TITLE
GITHub deployment failed

### ISSUE THREAD

**Issue by madhusudan1** [wedeploy/wedeploy.com#316]
> URL: /tutorials/lsna/deploy-static-files/

[msachatapp] Clone in progress [https://6c4102e4dc945b7aac5e0320041a927a2267732b@github.com/madhusudan1/tutorial-lsna#master]…
[msachatapp] Some error has happened during the build. Try again. [{"message":"Validation Error","status":400,"errors":[{"reason":"exceededPlanMaximum","context":{"message":"Desired service spec cpu exceeded the max limit for provided plan earlyAdopter. The max limit is 4","param":"cpu","value":{"key":5.666666666666667}}}]}].

**Comment by NolanChan** [comment]
Hi @madhusudan1 , could I ask what your project name is? Also, do you have any other services in your project?

**Comment by jonnilundy** [comment]
Hey @madhusudan1! Because of the inactivity, I am going to close this issue. Feel free to reach out to our customer service team by clicking the green button at the bottom corner of any of our sites. We would be glad to help!
