### ISSUE TITLE
Data demo on landing page has inconsistent behavior

### ISSUE THREAD

**Issue by christieyoo** [wedeploy/wedeploy.com#352]
I've noticed these inconsistent behaviors:

1. Data doesn't always load in the demo when I open or refresh the page.
![image](https://user-images.githubusercontent.com/14076448/32863877-df709a00-ca11-11e7-9b2d-66e68029881d.png)

2. Checking a filter checkbox is sometimes unresponsive.
<img width="781" alt="screen shot 2017-11-15 at 2 37 36 pm" src="https://user-images.githubusercontent.com/14076448/32864155-cbe58b70-ca12-11e7-9dd5-2b2a3a9a2a49.png">

3. Typing into the search bar is sometimes unresponsive.  
<img width="833" alt="screen shot 2017-11-15 at 2 34 56 pm" src="https://user-images.githubusercontent.com/14076448/32864035-783e5f60-ca12-11e7-902b-b8970960797c.png">

**Comment by jonathantneal** [comment]
I am getting **503** responses sporadically for the images and JSON, which would explain this issue. For instance, the last result on my opening page, **WWII in HD** returns this image:

https://images-tv.wedeploy.io/59c954237b859c85d070a56e.jpg

From devtools, I see that URL is showing me a page displaying the **503 / Service Unavailable** message. Hitting the URL individually in a new tab always works for me.

I’m not sure why, but I am also sometimes get a **No 'Access-Control-Allow-Origin' header** message. Here is an example:

```
Failed to load https://data-tv.wedeploy.io/shows?sort=%5B%7B%22rating%22%3A%22desc%22%7D%5D&aggregation=%5B%7B%22genres%22%3A%7B%22name%22%3A%22genres%22%2C%22operator%22%3A%22terms%22%7D%7D%2C%7B%22year%22%3A%7B%22name%22%3A%22years%22%2C%22operator%22%3A%22terms%22%7D%7D%5D&highlight=%5B%22name%22%5D&limit=12&offset=0&type=search&filter=%5B%7B%22and%22%3A%5B%7B%22name%22%3A%7B%22operator%22%3A%22prefix%22%2C%22value%22%3A%22princess%22%7D%7D%5D%7D%5D: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://0.0.0.0:3001' is therefore not allowed access. The response had HTTP status code 503.
common.js:1 Uncaught Error: Request terminated prematurely
```

**Comment by jonnilundy** [comment]
I'm not sure, but this might have something to do with this: https://github.com/wedeploy/engine/issues/863

**Comment by jonathantneal** [comment]
I am no longer seeing this error on https://wedeploy.com/

**Comment by jonathantneal** [comment]
@christieyoo, would you please confirm? 😃

**Comment by christieyoo** [comment]
@jonathantneal 
Looks good now!  And looks like the tests have been passing on CI.  I'll go ahead and close this.
