### ISSUE TITLE
'Try our demo' out of place

### ISSUE THREAD

**Issue by NolanChan** [wedeploy/wedeploy.com#388]
<img width="1376" alt="screen shot 2017-12-04 at 9 34 09 am" src="https://user-images.githubusercontent.com/1487616/33566993-9a02eb16-d8d6-11e7-89eb-143398d27e10.png">

**Comment by jonathantneal** [comment]
Hi @NolanChan, I’m sorry you’re seeing these things stacked over one another. Which browser are you using?

I’ve tested successfully in the following browsers:

- [X] Chrome 62
- [ ] Firefox 57 (I also see the issue here)
- [X] Safari 11.0.1

**Comment by NolanChan** [comment]
Hi Jon, 

I saw it in the latest firefox (57) as I just switched over 😅, guess it's not a big deal if Chrome and Safari are alright

**Comment by jonnilundy** [comment]
Hey @NolanChan @jonathantneal, is this issue still persisting?

**Comment by NolanChan** [comment]
Yup, still seeing it in Firefox 57.1 for me
