### ISSUE TITLE
Update copyright text to 2018

### ISSUE THREAD

**Issue by albertmourato** [wedeploy/wedeploy.com#417]
<img width="270" alt="screen shot 2018-02-03 at 6 40 30 pm" src="https://user-images.githubusercontent.com/19316913/35771834-c511076e-0911-11e8-8e2d-213c462a28cd.png">

**Comment by jonnilundy** [comment]
Fixed with https://github.com/wedeploy/wedeploy.com/commit/35012ed9155b6a8a933f668307e228a1f3ea5b74
