### ISSUE TITLE
Remove uncommon commands from CLI docs

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/wedeploy.com#420]
1. `logout`
2. `console`
3. `update`

**Comment by vitorfernandes** [comment]
why?

**Comment by zenorocha** [comment]
This is on https://wedeploy.com/docs/intro/using-the-command-line. There are too many commands over there and we're trying to highlight only the most used ones on the site. If people need to perform more specific commands, they can always type `we` and see them all.

**Comment by vitorfernandes** [comment]
Got it. Would be nice a specific page for explaining briefly all the commands.

**Comment by jonnilundy** [comment]
Ya, we could make something similar to API documentation that automatically generates descriptions for all the available commands.

**Comment by vitorfernandes** [comment]
Great! 👍

**Comment by zenorocha** [comment]
Fixed on #426
