### ISSUE TITLE
Progress Tracker is pretty innacurate

### ISSUE THREAD

**Issue by NolanChan** [wedeploy/wedeploy.com#421]
It seems like the Reading Progress Tracker is pretty inaccurate on some pages. In the picture below, I'm right at the second topic, but it says I've only finished up to half of the first.

<img width="1210" alt="screen shot 2018-02-07 at 4 49 31 pm" src="https://user-images.githubusercontent.com/1487616/35949551-eeed78b6-0c26-11e8-92ea-e1c86fcec7fc.png">

This is probably more an `electric` problem than a `wedeploy.com` problem, so I don't mind moving this issue over there if need be

**Comment by zenorocha** [comment]
Issue moved to [wedeploy/marble #78](https://github.com/wedeploy/marble/issues/78) via [**ZenHub**](https://www.zenhub.com/)
