### ISSUE TITLE
Sidebar shadow is broken on docs homepage

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#448]
<img width="353" alt="screen shot 2018-02-28 at 3 05 27 pm" src="https://user-images.githubusercontent.com/23219848/36818225-faaf7122-1c98-11e8-91cf-223faa86214c.png">

**Comment by zenorocha** [comment]
This looks broken on electricjs.com as well.

<img width="430" alt="screen shot 2018-03-08 at 3 58 31 pm" src="https://user-images.githubusercontent.com/398893/37183198-b31760a2-22e9-11e8-9b21-a12fbe563902.png">

**Comment by zenorocha** [comment]
Issue moved to [wedeploy/marble #77](https://github.com/wedeploy/marble/issues/77) via [**ZenHub**](https://www.zenhub.com/)
