### ISSUE TITLE
Stars on landing page rating demo are repeated

### ISSUE THREAD

**Issue by henvic** [wedeploy/wedeploy.com#504]
See:
<img width="713" alt="screen shot 2018-04-12 at 10 35 39" src="https://user-images.githubusercontent.com/936421/38693957-4871944c-3e3d-11e8-8af1-538c89b289f3.png">

**Comment by jonnilundy** [comment]
@henvic I'm not seeing what you mean...

**Comment by henvic** [comment]
@jonnilundy see the repeated "rating" part of the bottom left. There should be five stars, not 25.

**Comment by jonnilundy** [comment]
I thought this was intentional. @vitorfernandes?

**Comment by vitorfernandes** [comment]
go to amazon, type wine and scroll down to see the same pattern. it's a common pattern @henvic.
