### ISSUE TITLE
Update Feature Overview section in docs

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#506]
https://wedeploy.com/docs/intro/feature-overview/
This section is one of our main value propositions and is outdated.

**Comment by albertmourato** [comment]
I totally agree.
I would like to help you if you need.

**Comment by jonnilundy** [comment]
Thanks @albertmourato! I think its best to wait until we have @fareias with us fully. It would be nice to have his input.

**Comment by jonnilundy** [comment]
But if you could start a list of features you see, that would be helpful!

**Comment by jonnilundy** [comment]
closed in favor of #547
