### ISSUE TITLE
Update Screenshots of Tutorials

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/wedeploy.com#510]
It's still showing as: 

<a href="https://cl.ly/2P0F3W233f0V" target="_blank"><img src="https://dha4w82d62smt.cloudfront.net/items/3J3C1G1K3r0a3n2H3f0u/Screen%20Shot%202018-04-16%20at%204.26.53%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by jonnilundy** [comment]
Hm, very interesting. It looks like it's been merged but not published (even though the commit is on the production branch). I'm redeploying now to see if that works. 

Prod: https://wedeploy.com/images/tutorials/it-works.png
Staging: https://staging.wedeploy.io/images/tutorials/it-works.png

**Comment by jonnilundy** [comment]
K, after the redeployment, it looks like it works now. Let me know if you notice anything else though! Can you verify and close?

**Comment by pragmaticivan** [comment]
It's working now, thanks!
