### ISSUE TITLE
Filtering and Sorting Data Docs have incorrect CURL request

### ISSUE THREAD

**Issue by NolanChan** [wedeploy/wedeploy.com#525]
https://wedeploy.slack.com/archives/C2MGG7AJ3/p1525114308000503?thread_ts=1525113586.000318&cid=C2MGG7AJ3

The CURL request should be a `GET` request instead of a `POST` request. I printed out the URL locally for the filtering example:

`https://<serviceid>-<projectid>.wedeploy.io/movies?filter=[{"or":[{"and":[{"year":{"operator":"<","value":2000}}]},{"rating":{"operator":">","value":8.5}}]}]` 

but we will need to URL-encode the `filter` query param:

`filter%3D%5B%7B%22or%22%3A%5B%7B%22and%22%3A%5B%7B%22year%22%3A%7B%22operator%22%3A%22%3C%22%2C%22value%22%3A2000%7D%7D%5D%7D%2C%7B%22rating%22%3A%7B%22operator%22%3A%22%3E%22%2C%22value%22%3A8.5%7D%7D%5D%7D%5D`

**Comment by zenorocha** [comment]
Any updates on this?

**Comment by victorlaerte** [comment]
@zenorocha Not yet Zeno, I still on Spain working on Screens for 7.1 release. I believe until next Wednesday I can take a look, sorry.
