### ISSUE TITLE
Update commands on landing page's console

### ISSUE THREAD

**Issue by henvic** [wedeploy/wedeploy.com#53]
The "Available Commands" is going to be totally outdated at the beginning of next week.

1. `we create` is going to be renamed as `we generate`
2. `we dev` replaces `we run`, `we link`, `we unlink`, and `we stop`

Maybe show instead:
1. `we generate`
2. `we dev`
3. `we list`

**Comment by jonnilundy** [comment]
@henvic Can you let me know when you have finished the commands for the new CLI so I can work on the documentation? Thanks!
