### ISSUE TITLE
Add anchors to Configuring Data just like we do for Configuring Deployments

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/wedeploy.com#558]
Configuring Data: https://wedeploy.com/docs/data/configuring-data/#2

See how we do on Configuring Deployments: https://wedeploy.com/docs/deploy/configuring-deployments/#2

**Comment by jonnilundy** [comment]
Do you just want to rename that section from `JSON attributes` to `Configuring Data`?

**Comment by jonnilundy** [comment]
Or are you refering to section links like this?

![image](https://user-images.githubusercontent.com/23219848/40440412-d7e2a102-5e72-11e8-97cd-736c8e9f8e0f.png)

**Comment by zenorocha** [comment]
No, I want links in the `JSON Attributes` table just like `Reference` has.

**Comment by jonnilundy** [comment]
Ooooh. Awesome!
