### ISSUE TITLE
Document new method `fields` for fetching only specified fields from the document

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/wedeploy.com#562]

**Comment by albertmourato** [comment]
Hey @zenorocha I'm not able to use this method.
Was it released yet?

**Comment by zenorocha** [comment]
@albertmourato it has been released in the newest version of WeDeploy Data image and now it's available for all SDKs. Can you add to the docs?

**Comment by albertmourato** [comment]
@zenorocha 
This issue is blocked by:
https://github.com/wedeploy/cdn/pull/51
and
https://github.com/wedeploy/wedeploy.com/pull/565
