### ISSUE TITLE
Invalid credentials.

### ISSUE THREAD

**Issue by chenchenSG** [wedeploy/wedeploy.com#593]
I am using Windows 10

I followed the steps at 
https://wedeploy.com/tutorials/liferay-dxp/deploy-project/

I first have successfully logged into We deploy. I followed the steps, and i was stuck at 
running this code  "we deploy -p projectID"

error message is Invalid credentials.
![err](https://user-images.githubusercontent.com/33998474/41094077-993917ba-6a7f-11e8-91e6-684e7ae502ae.JPG)

**Comment by zenorocha** [comment]
Issue moved to [wedeploy/support #23](https://github.com/wedeploy/support/issues/23) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zenorocha** [comment]
Thanks @chenchenSG, we're going to analyze the problem.
