### ISSUE TITLE
Cannot click on /blog header link from mobile

### ISSUE THREAD

**Issue by eduardolundgren** [wedeploy/wedeploy.com#64]
Note that the blog link is not anywhere in the header.

<img width="432" alt="screen shot 2017-02-16 at 9 19 03 am" src="https://cloud.githubusercontent.com/assets/113087/23032388/0ad70e14-f429-11e6-98b8-193ef6b50556.png">

**Comment by ygorcosta** [comment]
Here is the vitor's solution to mobile.
![image](https://cloud.githubusercontent.com/assets/19154228/23033546/56a3101e-f42d-11e6-949f-0e7bcc57193e.png)

**Comment by zenorocha** [comment]
That's true. We need a responsive menu asap.

**Comment by ygorcosta** [comment]
Done https://github.com/wedeploy/wedeploy.com/commit/02ace87e4a1780ef1274b8d195ab508af45d863d
