### ISSUE TITLE
Site isn't working

### ISSUE THREAD

**Issue by hectorgrecco** [wedeploy/wedeploy.com#641]
Hey guys, when I access wedeploy.com, it returns me a 404 error. Have you seen that?

**Comment by zenorocha** [comment]
Hey @hectorgrecco, we're aware, please track the incident at status.wedeploy.com

**Comment by hectorgrecco** [comment]
![image](https://user-images.githubusercontent.com/10110093/42473107-0a1164fa-839a-11e8-8e05-cabbb5b2866d.png)

Thanks =)
