### ISSUE TITLE
Error in customDomainDnsVerification (DNSSEC)

### ISSUE THREAD

**Issue by dorcilio** [wedeploy/wedeploy.com#682]
I'm trying to set up WeDeploy with a Google domain, but I've tried several configuration options and none succeeded.

Console error:
`"Ensure progeta.app resolves to dns.wedeploy.com via A, CNAME or ALIAS."`

Message in DNSSEC (Google):
`{
  "Status": 2,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "progeta.app.",
      "type": 1
    }
  ],
  "Comment": "Name servers refused query (lame delegation?) [91.109.245.139, 173.255.231.87, 37.123.115.172, 173.255.215.107, 178.62.47.76, 188.226.197.55]."
}`

Note:
There is a DNSSEC configuration section in Google Domains, but I did not find anything about generating a key or anything like that in the WeDeploy documentation.

Regards,
Dorcílio Neto.

**Comment by albertmourato** [comment]
Problem solved by using Cloudflare.
