### ISSUE TITLE
Update Email service environment variables

### ISSUE THREAD

**Issue by albertmourato** [wedeploy/wedeploy.com#696]
We noticed that all environment variables to this container starts with `WEDEPLOY_`. However, none of them is documented with this prefix.

**Comment by jonnilundy** [comment]
Interesting. I'm wondering if they changed?

**Comment by albertmourato** [comment]
I remember last year there was a task to rename all WeDeploy-related environment variables to use the prefix `WEDEPLOY_`. I think they changed it but we didn't update the docs. I'm doing this now.

**Comment by albertmourato** [comment]
Closing due WeDeploy depreciation.
