### ISSUE TITLE
First line of code block in Tutorials is not indenting

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#76]
First line of code block is not indenting in the Tutorials. 

In this example, all lines are indented the same but the first line gets compiled differently. I also tried switching the indent format from tabs to spaces and it made no difference. 

<img width="622" alt="screen shot 2017-03-06 at 10 18 07 am" src="https://cloud.githubusercontent.com/assets/23219848/23623267/4963b188-0256-11e7-8fc9-867b81717be2.png">

**Comment by zenorocha** [comment]
Fixed, thanks @Robert-Frampton!
