### ISSUE TITLE
Landing page footer broken on Safari

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#78]
<img width="663" alt="screen shot 2017-03-06 at 5 17 38 pm" src="https://cloud.githubusercontent.com/assets/23219848/23637490/d843eb54-0290-11e7-8fd5-c45c570ebca6.png">

**Comment by zenorocha** [comment]
I can confirm this bug, can you fix it @ygorcosta?

**Comment by ygorcosta** [comment]
Yes!
