### ISSUE TITLE
Explain how to deploy an already existing application

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/wedeploy.com#80]
<a href="https://github.com/ipeychev"><img src="https://avatars0.githubusercontent.com/u/78014?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ipeychev](https://github.com/ipeychev)**
_Friday Jan 06, 2017 at 07:58 GMT_
_Originally opened as https://github.com/wedeploy/docs/issues/64_

----

We have to add to the docs information about how to deploy an already existing application.

At the moment, when reading the documentation about the [hosting service](https://github.com/wedeploy/docs/blob/b13c4c48623ad60359f716e970ae7328ac90c5d0/hosting/index.md), the developer gets the impression that the recommended (or the only) way of deploying the app is to fork a boilerplate and commit its content to WeDeploy's Git server.

Although this is a valid scenario, in many cases this would be an extra step, which the developers would prefer to avoid. In most of the cases the developer works on his project and at some point he decides to deploy it. The recommended way of forking a boilerplate gives the impression to the developer that he should have two repositories - one where he develops and another one (the forked boilerplate) where he has to put the content which will be deployed.

Obviously this is an incorrect assumption and that's why `project.json` and `container.json` exist. They are documented [here](https://github.com/wedeploy/docs/blob/b13c4c48623ad60359f716e970ae7328ac90c5d0/intro/configuration-files.md), but there is no relation between them and the documentation of the services, so the developer cannot figure out how to use `project.json` and `container.json` in his own project.

Apart from adding a relation between these and the documentation of the different services, it would be good to have a separate section in the docs, where we take an existing project and explain how to add to it the different services. From these e can create videos on YouTube and embed them to the docs.

**Comment by jonnilundy** [comment]
I think our new "[Getting Started](http://wedeploy.com/docs/hosting/getting-started.html)" pages for each service [at least partially] fixes this issue by including a link to [our page](http://wedeploy.com/docs/intro/how-it-works.html) about config files. I agree we need more resources to show how devs can deploy existing apps.
