### ISSUE TITLE
Document WEDEPLOY_WEB_PATH env variable

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/wedeploy.com#81]
<a href="https://github.com/ipeychev"><img src="https://avatars0.githubusercontent.com/u/78014?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ipeychev](https://github.com/ipeychev)**
_Friday Jan 06, 2017 at 08:05 GMT_
_Originally opened as https://github.com/wedeploy/docs/issues/65_

----

When developing an application, the output is often produced from some build process.
This could be a Gulp/Grunt task and the result is usually in a folder called `out` or `dist`. In this case, `index.html` won't be in the main folder, but in `dist` or `out`.

We have to add to the [documentation](https://github.com/wedeploy/docs/blob/b13c4c48623ad60359f716e970ae7328ac90c5d0/hosting/index.md) information about how to specify where the output result is. This is the purpose of `WEDEPLOY_WEB_PATH` environment variable. Its value specifies where WeDeploy hosting service will look for the files.

**Comment by zenorocha** [comment]
Thanks a lot for this feedback @ipeychev, here's what we've done to highlight this piece a little bit more:

http://wedeploy.com/docs/hosting/environment-variables.html
http://wedeploy.com/blog/3-reasons-why-you-should-use-environment-variables.html

Feel free to send any suggestions!
