### ISSUE TITLE
Document the hooks inside container.json

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/wedeploy.com#83]
<a href="https://github.com/ipeychev"><img src="https://avatars0.githubusercontent.com/u/78014?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ipeychev](https://github.com/ipeychev)**
_Friday Jan 06, 2017 at 11:57 GMT_
_Originally opened as https://github.com/wedeploy/docs/issues/67_

----

Currently the hooks inside `container.json` are [not documented](https://github.com/wedeploy/docs/blob/b13c4c48623ad60359f716e970ae7328ac90c5d0/intro/configuration-files.md).

We have to document them and describe possible use cases.

**Comment by jonnilundy** [comment]
@ipeychev We recently added examples of hooks inside the "Getting Started" pages for the services that use hooks ([Node.js for example](http://wedeploy.com/docs/other/nodejs.html)). Is this adequate or do we need a section dedicated to documenting how to use hooks?
