### ISSUE TITLE
Document how to add users with roles

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/wedeploy.com#85]
<a href="https://github.com/ipeychev"><img src="https://avatars0.githubusercontent.com/u/78014?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ipeychev](https://github.com/ipeychev)**
_Tuesday Jan 17, 2017 at 21:45 GMT_
_Originally opened as https://github.com/wedeploy/docs/issues/71_

----

The process of adding users with roles has to be added to the documentation.

**Comment by jonnilundy** [comment]
This should be easier now with https://github.com/wedeploy/demo-user-roles

**Comment by jonnilundy** [comment]
@NolanChan might be able to handle this since we built the user role demo.

**Comment by jonnilundy** [comment]
Closed with #443
