### ISSUE TITLE
Document the email confirmation after registration

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/wedeploy.com#86]
<a href="https://github.com/ipeychev"><img src="https://avatars0.githubusercontent.com/u/78014?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ipeychev](https://github.com/ipeychev)**
_Tuesday Jan 24, 2017 at 11:58 GMT_
_Originally opened as https://github.com/wedeploy/docs/issues/72_

----

After the implementation of https://github.com/wedeploy/api-js/issues/79, we have to update the documentation to describe the API.

**Comment by jonnilundy** [comment]
Thanks, Iliyan! Since this is not a capability that developers can implement in their own WeDeploy projects, I don't think we should add it to the documentation.
