### ISSUE TITLE
Document how to protect a collection

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/wedeploy.com#87]
<a href="https://github.com/ipeychev"><img src="https://avatars0.githubusercontent.com/u/78014?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ipeychev](https://github.com/ipeychev)**
_Tuesday Jan 31, 2017 at 14:11 GMT_
_Originally opened as https://github.com/wedeploy/docs/issues/74_

----

Docs currently lack information how to protect a collection to be accessed only by authenticated user. 

For example, the following code will forbid anonymous requests to `boards` collection by checking if the field `userId` in the `boards` collection matches the Id of currently authenticated user:
```json
[
  {
    "data": true,
    "path": "/boards",
    "parameters": {
      "filter": {
        "value": {"userId":{"operator":"=","value":"$auth.id"}}
      }
    }
  }
]
```

**Comment by jonnilundy** [comment]
Closed by #443
