### ISSUE TITLE
Error after leaving the logged area

### ISSUE THREAD

**Issue by marceloogeda** [wedeploy/wedeploy.com#88]
Hi guys!

Congrats, I really like work you're doing with wedeploy. It looks amazing!

Unfortunately, I have caught an error after leaving the logged area.

I'll describe it using the concept of BDD

**Scenario:** Error after leaving the logged area
  **Given** I'm logged in with my Github account
  **When** I did the logout
  **Then** I get this error: 401 Unauthorized

And the same thing happens when I go to the login page after seeing this error.

<img width="1280" alt="screen shot 2017-03-10 at 7 48 32 pm" src="https://cloud.githubusercontent.com/assets/3205036/23816260/9beee87e-05ca-11e7-8544-4c7873c36d53.png">

I hope that helped you.

**Comment by zenorocha** [comment]
This problem has been fixed now, thank you @marceloogeda for reporting :)

**Comment by marceloogeda** [comment]
Awesome! thank you ;)
