### ISSUE TITLE
Need error/feedback when data container fails to load

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy.com#90]
I inputted an unsupported api parameter and the data container failed to load when I tried to link my project. We need to add an error message to let the user know what is wrong.

To reproduce:
Paste this into your `api.json` and run the project locally.
```
[
	{
		"path": "/*",
		"parameters": {
			"item": {
				"type": "integer"
			}
		}
	}
]
```

**Comment by zenorocha** [comment]
@jonnilundy can you close this issue and post on the appropriate repository?
