### ISSUE TITLE
Support pigments for code blocks in markdown

### ISSUE THREAD

**Issue by mdelapenya** [wedeploy/wedeploy.com#93]
Markdown syntax highlighting is not showing colors even though I specify the language (java and json)

**Comment by zenorocha** [comment]
Fixed https://github.com/wedeploy/wedeploy.com/commit/3e42809b7d125243c15e05d48d1107ed09fb3fdb

For Java highlighting make sure to use:

```
```text/x-java
import com.demo.util.MyType;
import com.demo.util.MyInterface;

public enum Enum {
  VAL1, VAL2, VAL3
}
```

And for JSON highlighting make sure to use:

```
```application/json
{
	"id": "auth",
	"name": "Auth",
	"type": "wedeploy/auth"
}
```

**Comment by jmnavarro** [comment]
Hey, remember we'll need support for Swift as well!

**Comment by zenorocha** [comment]
Done! Make sure to use the following code to apply it.

```
```text/x-swift
```

<img width="557" alt="screen shot 2017-03-18 at 9 14 34 am" src="https://cloud.githubusercontent.com/assets/398893/24073840/6a489c24-0bbb-11e7-96b9-69ec26f338c7.png">
