### ISSUE TITLE
Unexpected behavior at readingProgress

### ISSUE THREAD

**Issue by marceloogeda** [wedeploy/wedeploy.com#99]
Note that reading progress hides ahead of time.

![qcykxhxrx7](https://cloud.githubusercontent.com/assets/3205036/24163532/9e805744-0e49-11e7-82bc-3a929133da15.gif)

**Comment by ygorcosta** [comment]
Thanks for reporting @marceloogeda.
We've noticed this problem. There is a [issue](https://github.com/metal/metal-reading-progress/issues/1) opened already.

Feel free to find/open more issues @marceloogeda! We'll be a pleasure to solve them! =)

**Comment by marceloogeda** [comment]
Great! I didn't know that it belongs to another issue.
Thank you @ygorcosta. Will be a pleasure to help you!

**Comment by ygorcosta** [comment]
I'm closing this issue.
You can follow this fix [here](https://github.com/metal/metal-reading-progress/issues/1)
